### DISCUSSION TITLE
GitHub Releases

### DISCUSSION THREAD

**Discussion by abuechler** [allegro/axion-release-plugin#914] [Q&A] [answered]
Hello,

I'm trying to figure out how to use the plugin together with GitHub releases. We have a workflow that's triggered on the release event. We're using the latest version 1.18.8 of the plugin and also have the setting 

```
scmVersion {
    unshallowRepoOnCI.set(true)
}
```

The workflow is doing a Gradle build and passing a forceVersion:

```
./gradlew build release -Prelease.forceVersion=31.0.0
```

everything is good until the `verifyRelease` fails with error:

```
Branch 71b4cc0423eb401fe54eb318787697101294aed2 is not set to track another branch
```

How do you handle that a GitHub release already creates a Git tag? How do you let it build on a tag, do you disable all checks for that?

**Comment by bgalek** [comment]
hi! @abuechler
This what works for me (assiming: releaseOnlyOnReleaseBranches.set(true) and unshallowRepoOnCI.set(true))

```
name: Library Release

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew publish
```

you can see how this repo handles itself :) https://github.com/allegro/axion-release-plugin/blob/main/.github/workflows/publish.yml

Basically, when github release is created you already have the tag on last commit, so you don't need to create another release.
