### ISSUE TITLE
TransportException after upgrade to 1.13.X

### ISSUE THREAD

**Issue by bluepixbe** [allegro/axion-release-plugin#515]
Hi all,

Due to the update of gradle to 7.5 we had to update the axion plugin 1.12.1 to 1.13.14 as well. Everything seems to run smooth apart from pushing the tag to git (GitLab 15.0.4).

```
Pushing all to remote: origin
Exception occurred during push: org.eclipse.jgit.api.errors.TransportException: https://gitlab-ci-token@xxx: git-receive-pack not permitted on 'https://gitlab-ci-token@xxxx.git/'
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':release'.
> org.eclipse.jgit.api.errors.TransportException: https://gitlab-ci-token@xxx.git: git-receive-pack not permitted on 'https://gitlab-ci-token@xxx.git/'
```

I checked the documentation but I was not able to find any breaking changes in regards to the authentication. 

We invoke the release as follow
```
script:
   - git checkout master
   - gradle release -Prelease.versionIncrementer=$INCREMENTOR -PbinRepositoryUsername=$REGISTRY_USERNAME -PbinRepositoryPassword=$REGISTRY_PASSWORD -Prelease.customUsername=$GIT_USERNAME -Prelease.customPassword=$GIT_PASSWORD -Prelease.useHighestVersion
```

Do you have any hints? Unfortunately a rollback to 1.12.1 is not an option as the versionConfig is not compliant with gradle 7.X

Any help is really appreciated!

**Comment by bgalek** [comment]
@bluepixbe hi! do you have the same problem when cloning via ssh?

**Comment by bluepixbe** [comment]
@bgalek Thanks for your quick reply. 
Unfortunately for access tokens you can not use ssh. Or at least I haven't found a way in GitLab. Or did you meant something else?

**Comment by bgalek** [comment]
Just checking - https://axion-release-plugin.readthedocs.io/en/latest/configuration/ci_servers/#gitlab-ci have you checked that out?

**Comment by bluepixbe** [comment]
@bgalek Awesome thanks a lot for the hint. This fixed the issue. 
TBH I was going through the change log and fixed the breaking changes and after having the authentication issue I was just checking the authentication documentation and not the CI part.

So just for others
With 1.12.X (and I guess before) the following was working:
```
gradle_release:
  stage: release
  variables:
    <<: *variables
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script:
    - git checkout master
    - gradle release -Prelease.versionIncrementer=$INCREMENTOR -PbinRepositoryUsername=$REGISTRY_USERNAME -PbinRepositoryPassword=$REGISTRY_PASSWORD -Prelease.customUsername=$GIT_USERNAME -Prelease.customPassword=$GIT_PASSWORD -Prelease.useHighestVersion
```

With 1.13.X I had to change to:
```
gradle_release:
  stage: release
  variables:
    <<: *variables
  script:
    - git remote set-url origin ${CI_SERVER_URL}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git
    - gradle release -Prelease.disableChecks -Prelease.pushTagsOnly -Prelease.versionIncrementer=$INCREMENTOR -PbinRepositoryUsername=$REGISTRY_USERNAME -PbinRepositoryPassword=$REGISTRY_PASSWORD  -Prelease.customUsername=$GIT_USERNAME -Prelease.customPassword=$GIT_PASSWORD -Prelease.useHighestVersion
```

So I'm closing the issue.
