### ISSUE TITLE
With GitLab publish a "snapshot" with the feature branch name in the version

### ISSUE THREAD

**Issue by javaworkinggirl** [allegro/axion-release-plugin#605]
Hi.  I am on version 1.15.0 of the axion release plugin.

When I am on my local machine and on a branch and publish to my gitlab maven repo, I get version: 0.1.2-feature-blah-2-SNAPSHOT, where blah-2 is my branch name.  That's what I want.

However, since GitLab does checks out on detached head and not branches, how do I publish "snapshot"s with the branch name from GitLab CICD?  So far when I try on GitLab, I am missing feature branch name in the version.  I am getting for example: 0.1.2-SNAPSHOT.

We need this or something like it to avoid having collisions when many developers are working on the same project and doing dev integration testing of unmerged to main code.

I tried adding git remote set-url command  and that did not work.

Other suggestions?   Thank you.

Snippet from .gitlab-ci.yml:
```
publish-snapshot:
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .gradle/caches
  image: gradle:jdk17
  stage: build
  needs: [ "lint-compile-test" ]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || ($CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push")
  tags:
    - dev
  script:
    - git remote set-url origin ${CI_SERVER_URL}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git
    - gradle fte-1605-alpha:publishAlphaPublicationToXXXCIRepository
    - gradle fte-1605-alpha-api:publishAlpha-apiPublicationToXXXCIRepository

```
