### ISSUE TITLE
-Prelease.overriddenBranchName=xxx is ignored

### ISSUE THREAD

**Issue by ddeath** [allegro/axion-release-plugin#885]
When publishing with `./gradlew publish -Prelease.overriddenBranchName="breaking/asd"` `overriddenBranchName` parameter is ignored. This is happening in github when we want to publish from main branch.
This is because of this line: https://github.com/allegro/axion-release-plugin/blob/48ba8e133a8e9de77b2a02910182aa378210003c/src/main/java/pl/allegro/tech/build/axion/release/infrastructure/git/GitRepository.java#L390 in other words `overriddenBranchName` is only considered if we are in detached state.

We want to use it on main branch since we are releasing after merge. But that means that branch versioning does not work because it will always be `main` branch. So idea was to use `overriddenBranchName` but that does not work either...

**Comment by bgalek** [comment]
hi! 
I would use unshallowing + releaseBranchNames feature.

enable it by:
```
scmVersion {
    unshallowRepoOnCI.set(true)
}
```
With this setup, `./gradlew release` will do release `main` or `master` (it's configurable) branch names, others will result with snapshots.

**Comment by ddeath** [comment]
I dont see how it would help in my scenario. I tried to used `unshallowRepoOnCI` but it has no effect.

axion-release-plugin does not have access to original branch name if it is running on main branch. That is why I want to use `overriddenBranchName` feature.

"workaround" for this is to use:
```
  - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}
```

With that `overriddenBranchName` will work because above code will switch git to "Detached" mode aka "HEAD" at least that is my understanding of what is happening

**Comment by ddeath** [comment]
Maybe to make it even more clear. Here is our setup:
```
scmVersion {
    repository {
        directory = "${layout.projectDirectory}/../.."
    }
    tag {
        prefix.set("chewy-steak-service-")
    }
    versionCreator("simple")
    snapshotCreator { _, _ -> "" }
    branchVersionIncrementer.putAll(
        mapOf(
            "breaking/.*" to "incrementMajor",
            "feature/.*" to "incrementMinor",
            "fix/.*" to "incrementPatch",
            "bugfix/.*" to "incrementPatch",
        ),
    )
}
```

If I create PR where I want to merge branch `breaking/NOJIRA/testing` into `main` then If we run `./gradlew publish` on main branch after merge, it will NOT increment major version and also that `overriddenBranchName` does not work until we apply "workaround" specified in previous post

**Comment by bgalek** [comment]
axion release plugin actually integrates with github, 
`fetch-depth: 0` and `ref: ${{ github.sha }}` is not needed anymore in github actions environment

**Comment by bgalek** [comment]
assiming: `releaseOnlyOnReleaseBranches.set(true)` and `unshallowRepoOnCI.set(true)` 
example workflow:

```yml
name: Service Release

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      released-version: ${{ steps.release.outputs.released-version }} # optional if you want to log it or smth
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build
      - run: ./gradlew release
        id: release
      - run: ./gradlew publish
```

```yml
name: Library Release

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew publish
```
